[[services]]
name = "auth"
id = 1

[[services.endpoints]]
name = "AuthEndpointExample" # Replace with actual endpoint name for the auth service
description = "Description of the auth endpoint." # Add description for auth endpoint
code = 10000  # Replace with actual endpoint code for the auth service

[[services.endpoints.parameters]]
name = "auth_param" # Example parameter for auth endpoint
ty = { Optional = { String = {} } }

[[services.endpoints.returns]]
name = "auth_result" # Example return for auth endpoint
ty = { String = {} }

[[services]]
name = "user"
id = 2

[[services.endpoints]]
name = "UserListEvents"
description = "Retrieves a list of user events." # Description for UserListEvents endpoint
code = 20010

[[services.endpoints.parameters]]
name = "kind"
ty = { Optional = { Int = {} } }

[[services.endpoints.parameters]]
name = "limit"
ty = { Optional = { Int = {} } }

[[services.endpoints.parameters]]
name = "offset"
ty = { Optional = { Int = {} } }

[[services.endpoints.returns]]
name = "total"
ty = { BigInt = {} }

[[services.endpoints.returns]]
name = "events"
ty = { DataTable = { name = "UserListEventsRow", fields = [
    { name = "event_id", ty = { BigInt = {} } },
    { name = "kind", ty = { Int = {} } },
    { name = "severity", ty = { Int = {} } },
    { name = "chain_id", ty = { Int = {} } },
    { name = "block_id", ty = { BigInt = {} } },
    { name = "block_time", ty = { BigInt = {} } },
    { name = "transaction_hash", ty = { BlockchainTransactionHash = {} } },
    { name = "from_address", ty = { BlockchainAddress = {} } },
    { name = "contract_address", ty = { BlockchainAddress = {} } },
    { name = "detail", ty = { Object = {} } },
    { name = "signals", ty = { Vec = { Int = {} } } },
    { name = "signal_kinds", ty = { Vec = { Int = {} } } },
]} }

[[services.endpoints]]
name = "UserListSignals"
description = "Retrieves a list of user signals." # Description for UserListSignals endpoint
code = 20020

[[services.endpoints.parameters]]
name = "kind"
ty = { Optional = { Int = {} } }

[[services.endpoints.parameters]]
name = "signal_id"
ty = { Optional = { BigInt = {} } }

[[services.endpoints.parameters]]
name = "limit"
ty = { Optional = { Int = {} } }

[[services.endpoints.parameters]]
name = "offset"
ty = { Optional = { Int = {} } }

[[services.endpoints.returns]]
name = "total"
ty = { BigInt = {} }

[[services.endpoints.returns]]
name = "signals"
ty = { DataTable = { name = "UserListSignalsRow", fields = [
    { name = "signal_id", ty = { BigInt = {} } },
    { name = "kind", ty = { Int = {} } },
    { name = "chain_id", ty = { Int = {} } },
    { name = "block_id", ty = { BigInt = {} } },
    { name = "block_time", ty = { BigInt = {} } },
    { name = "transaction_hash", ty = { BlockchainTransactionHash = {} } },
    { name = "from_address", ty = { BlockchainAddress = {} } },
    { name = "contract_address", ty = { BlockchainAddress = {} } },
    { name = "detail", ty = { Object = {} } },
    { name = "value", ty = { Optional = { Numeric = {} } } },
    { name = "token", ty = { Optional = { String = {} } } },
    { name = "value_usd", ty = { Optional = { Numeric = {} } } },
]} }
